{
 "title": "Libvirt Dashboard",
 "description": "[ref](https://github.com/ycy1766/prometheus-libvirt-exporter)",
 "tags": [ "libvirt" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "project_name", "label": "project_name", "query": "label_values(project_name)" },
   {
    "name": "compute_node",
    "label": "host",
    "query": "label_values(libvirt_domain_info_memory_usage_bytes{projectName=\"$project_name\"}, host)"
   },
   {
    "name": "instance_id",
    "label": "uuid",
    "query": "label_values(libvirt_domain_info_memory_usage_bytes{projectName=\"$project_name\",host=~\"$compute_node\"}, instanceId)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance status",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "libvirt_domain_state_code{project_name=~\"$project_name\", host=~\"$compute_node\", instanceId=~\"$instance_id\"}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total maximum_memory_bytes  usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_maximum_memory_bytes{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"})"
    }
   ]
  },
  {
   "title": "Total vCPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_virtual_cpus{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"})"
    }
   ]
  },
  {
   "title": "libvirt_domain_info_cpu_time_seconds_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"}[5m])",
     "legendFormat": "cpu : {{name}}"
    }
   ]
  },
  {
   "title": "libvirt_domain_info_memory_usage_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_memory_usage_bytes{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"}",
     "legendFormat": "memory_usage_bytes : {{name}}"
    }
   ]
  },
  {
   "title": "Total memory_usage_bytes  usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_memory_usage_bytes{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"})"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block Read/Write Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_read_bytes_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"}[5m])",
     "legendFormat": "Read : {{name}}"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_write_bytes_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"}[5m])",
     "legendFormat": "Write : {{name}}"
    }
   ]
  },
  {
   "title": "Block Read/Write Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_read_requests_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"}[5m])",
     "legendFormat": "Read Requests : {{name}}"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_write_requests_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"}[5m])",
     "legendFormat": "Write  Requests : {{name}}"
    }
   ]
  },
  { "title": "Network Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "interface_stats_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_bytes_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"} [5m])",
     "legendFormat": "RX : {{name}}"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"} [5m])",
     "legendFormat": "TX : {{name}}"
    }
   ]
  },
  {
   "title": "Interface PPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_packets_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"} [5m])",
     "legendFormat": "RX Packets : {{name}}"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_packets_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"} [5m])",
     "legendFormat": "TX Packets : {{name}}"
    }
   ]
  },
  {
   "title": "Interface Error/Drop",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_drops_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"} [5m])",
     "legendFormat": "RX Drop : {{name}}"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_drops_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"} [5m])",
     "legendFormat": "TX Drop : {{name}}"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_errors_total{host=~\"$compute_node\",instanceId=~\"$instance_id\",job=~\"libvirt\"} [5m])",
     "legendFormat": "RX Error : {{name}}"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_errors_total{host=~\"$compute_node\",instanceId=~\"$instance_id\"} [5m])",
     "legendFormat": "TX Error : {{name}}"
    }
   ]
  }
 ]
}