---
- name: make sure grafana is down
  service:
    name: grafana-server
    state: stopped

- name: wait for grafana to be stopped
  wait_for:
    host: '{{ grafana_server_addr if ip_version == "ipv4" else grafana_server_addr[1:-1] }}'
    port: '{{ grafana_port }}'
    state: stopped

- name: make sure grafana configuration directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_gid }}"
  with_items:
    - "/etc/grafana/dashboards/openstack-dashboard"
    - "/etc/grafana/provisioning/datasources"
    - "/etc/grafana/provisioning/dashboards"
    - "/etc/grafana/provisioning/notifiers"
    - "/etc/grafana/provisioning/plugins"

- name: copy grafana dashboards
  copy:
    src: files/dashboards/
    dest: /etc/grafana/dashboards/openstack-dashboard/
    mode: '0644'

- name: write grafana.ini
  config_template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_gid }}"
    mode: 0640
    config_type: ini
    config_overrides: "{{ grafana_conf_overrides }}"

- name: write datasources provisioning config file
  template:
    src: datasources-openstack-dashboard.yml.j2
    dest: /etc/grafana/provisioning/datasources/openstack-dashboard.yml
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_gid }}"
    mode: 0640

- name: Write dashboards provisioning config file
  template:
    src: dashboards-openstack-dashboard.yml.j2
    dest: /etc/grafana/provisioning/dashboards/openstack-dashboard.yml
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_gid }}"
    mode: 0640

- name: copy grafana SSL certificate file
  copy:
    src: "{{ grafana_crt }}"
    dest: "/etc/grafana/openstack-dashboard.crt"
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_gid }}"
    mode: 0640
    remote_src: "{{ dashboard_tls_external | bool }}"
  when:
    - grafana_crt | length > 0
    - dashboard_protocol == "https"

- name: copy grafana SSL certificate key
  copy:
    src: "{{ grafana_key }}"
    dest: "/etc/grafana/openstack-dashboard.key"
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_gid }}"
    mode: 0440
    remote_src: "{{ dashboard_tls_external | bool }}"
  when:
    - grafana_key | length > 0
    - dashboard_protocol == "https"

- name: generate a Self Signed OpenSSL certificate for dashboard
  shell: |
    test -f /etc/grafana/openstack-dashboard.key -a -f /etc/grafana/openstack-dashboard.crt || \
    (openssl req -new -nodes -x509 -subj '/O=IT/CN=openstack-grafana' -days 3650 -keyout /etc/grafana/openstack-dashboard.key -out /etc/grafana/openstack-dashboard.crt -extensions v3_ca && \
    chown {{ grafana_uid }}:{{ grafana_uid }} /etc/grafana/openstack-dashboard.key /etc/grafana/openstack-dashboard.crt)
  when:
    - dashboard_protocol == "https"
    - grafana_key | length == 0 or grafana_crt | length == 0

- name: enable and start grafana
  service:
    name: grafana-server
    state: restarted
    enabled: true

- name: wait for grafana to start
  wait_for:
    host: '{{ grafana_server_addr if ip_version == "ipv4" else grafana_server_addr[1:-1] }}'
    port: '{{ grafana_port }}'
