---
galaxy_info:
  company: ISP RAS
  author: Artem Andryukhov
  description: Configures Libvirt Exporter
  license: Apache
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
dependencies: []
