---
- name: include_tasks systemd.yml
  include_tasks: systemd.yml

- name: start the libvirt_exporter service
  systemd:
    name: libvirt_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  failed_when: false
